- name: Configurar usuario SFTP con logging
  hosts: sftp
  become: true
  vars:
    nomenclatura: sftpuser_

  vars_prompt:
    - name: usuario_sftp
      private: false
      prompt: Introduce el nombre del usuario SFTP (sin la nomenclatura)
      salt_size: 8
      unsafe: false
  tasks:

    - name: Buscar último UID de usuarios con la nomenclatura
      shell: "grep '{{ nomenclatura }}' /etc/passwd | tail -n1 | cut -d: -f3"
      register: ultimo_usuario
      changed_when: false

    - name: comprobacion de si el usuario existe
      shell: "id -u {{ nomenclatura }}{{ usuario_sftp }}"
      register: usuario_existe
      failed_when: false
      changed_when: false

    - name: Crear usuario SFTP
      user:
        name: "{{ nomenclatura }}{{ usuario_sftp }}"
        group: sftp
        uid: "{{ ultimo_usuario.stdout | int + 1 if ultimo_usuario.stdout else 9000 }}"
        home: "{{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}"
        shell: /sbin/nologin
        create_home: yes
        state: present
      when: not usuario_existe.stdout

    - name: Configurar home seguro para chroot
      run_once: true
      file:
        path: "{{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}"
        owner: root
        group: sftp
        mode: "0755"
        state: directory
      when: not usuario_existe.stdout

    - name: Crear subdirectorio escribible para uploads
      run_once: true
      file:
        path: "{{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}/upload"
        owner: "{{ nomenclatura }}{{ usuario_sftp }}"
        group: sftp
        mode: "0755"
        state: directory
      when: not usuario_existe.stdout

    - name: Crear carpeta .ssh dentro del subdirectorio escribible
      run_once: true
      file:
        path: "{{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}/.ssh"
        owner: "{{ nomenclatura }}{{ usuario_sftp }}"
        group: sftp
        mode: "0700"
        state: directory
      when: not usuario_existe.stdout

    - name: crear claves para ssh
      command: "ssh-keygen -t ed25519 -f {{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}/.ssh/id_rsa -N ''"
      when: not usuario_existe.stdout

    - name: generar archivo authorized_keys
      run_once: true
      command: "cp {{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}/.ssh/id_rsa.pub {{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}/.ssh/authorized_keys"
      when: not usuario_existe.stdout

    - name: descargar clave en host
      fetch:
        run_once: true
        src: "{{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}/.ssh/id_rsa"
        dest: "./claves/{{ nomenclatura }}{{ usuario_sftp }}_id_rsa"
        flat: yes
      when: not usuario_existe.stdout

    - name: asegurar permisos 600 en la clave descargada
      file:
        path: "./claves/{{ nomenclatura }}{{ usuario_sftp }}_id_rsa"
        mode: "0600"
      delegate_to: localhost
      run_once: true
      when: not usuario_existe.stdout

    - name: crear carpeta de montaje en home del usuario SFTP
      run_once: true
      file:
        path: "{{ carpeta_compartida }}//{{ nomenclatura }}{{ usuario_sftp }}/dev"
        state: directory
        mode: '0771'
      when: not usuario_existe.stdout
    
    - name: Montar dev en la carpeta home del usuario SFTP
      mount:
        name: "{{ carpeta_compartida }}/{{ nomenclatura }}{{ usuario_sftp }}/dev"
        src: "{{ carpeta_compartida }}/dev"
        fstype: none
        opts: bind
        state: mounted
      when: not usuario_existe.stdout