- name: mi primer playbook
  hosts: all
  tasks:
    - name: guardar informacion de la cpu del sistema
      ansible.builtin.command: echo "prueba"
      register: top_info
      
    - name: mostrar la cpu info
      ansible.builtin.debug: 
        msg: "{{ top_info.stdout }}"
