- name: ejercicio3 gestion de usuarios
  hosts: [myhosts]
  become: true
  vars:
    usuario: "ejercicio3"
    passwd: "5566alvaro"
  tasks:
    - name: eliminar usuario si existe
      ansible.builtin.shell: | 
        if id "{{ usuario }}" &>/dev/null; then
          userdel "{{ usuario }}"
        fi

    - name: crear usuario
      ansible.builtin.command: "useradd {{ usuario }}"

    - name: cambiar el passwd
      ansible.builtin.command: "echo \"{{ usuario }}:{{ passwd }}\" | sudo chpasswd"
