- name: Instalar WordPress en servidor web # TENGO QUE TENER LA BASE DE DATOS YA CREADA Y CONFIGURADA PARA QUE FUNCIONE
  hosts: prueba
  become: true
  vars:
    wp_install_dir: /var/www/html/wordpress
    wp_archive_url: https://es.wordpress.org/latest-es_ES.tar.gz
    wp_db_name: "" # nombre de la base de datos en el cluster Galera
    wp_db_user: "" # usuario con permisos en la base de datos
    wp_db_password: "" # contraseña del usuario de la base de datos
    wp_db_host: "" # dirección IP o hostname del balanceador HAProxy que apunta al cluster Galera, ej: 192.168.100.10
    wp_url: "" # URL pública del sitio WordPress, ej: http://mi-wordpress.ejemplo.com
  tasks:
    - name: Instalar paquetes web y PHP
      ansible.builtin.yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - php-xml
          - php-mbstring
          - unzip
          - wget
        state: present

    - name: abrir puerto HTTP en firewalld
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        immediate: true
        state: enabled

    - name: desactivar SELinux en el arranque
      ansible.builtin.replace:
        path: /etc/selinux/config
        regexp: '^SELINUX=enforcing'
        replace: 'SELINUX=permissive'

    - name: desactivar SELinux 
      ansible.builtin.command: setenforce 0
      when: ansible_selinux.status == "enabled"
        
    - name: Iniciar y habilitar Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: Descargar WordPress temporalmente
      ansible.builtin.get_url:
        url: "{{ wp_archive_url }}"
        dest: /tmp/wordpress.tar.gz
        mode: '0644'

    - name: Extraer WordPress
      ansible.builtin.unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Crear directorio de instalación si no existe
      ansible.builtin.file:
        path: "{{ wp_install_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: '0755'
      
    - name: Copiar archivos WordPress al directorio de instalación
      ansible.builtin.copy:
        src: /tmp/wordpress/
        dest: "{{ wp_install_dir }}/"
        owner: apache
        group: apache
        mode: '0755'
        remote_src: yes

    - name: Crear wp-config.php apuntando a la BD remota
      ansible.builtin.template:
        src: templates/wp-config.php.j2
        dest: "{{ wp_install_dir }}/wp-config.php"
        owner: apache
        group: apache
        mode: '0644'
      vars:
        db_host_override: "{{ wp_db_host }}"

    - name: Ajustar permisos (propietario apache)
      ansible.builtin.file:
        path: "{{ wp_install_dir }}"
        state: directory
        recurse: yes
        owner: apache
        group: apache
        mode: '0755'

    - name: Reiniciar Apache
      ansible.builtin.service:
        name: httpd
        state: restarted