[myhosts]
trabajo-Virtualbox 	ansible_host=192.168.10.5	ansible_user=alvaro
trabajo-VMware	ansible_host=192.168.15.5	ansible_user=alvaro
[pruebas]
prueba-rocky	ansible_host=192.168.15.128	ansible_user=alvaro
