[myhosts]
trabajo-Virtualbox 	ansible_host=192.168.10.5	ansible_user=alvaro
trabajo-VMware	ansible_host=192.168.15.5	ansible_user=alvaro
[pruebas]
prueba-rocky	ansible_host=192.168.15.128	ansible_user=alvaro
[playbookUsrVar]
equipo1	ansible_host=192.168.15.129 ansible_user=alvaro
equipo2	ansible_host=192.168.15.5	ansible_user=alvaro
equipo3	ansible_host=192.168.15.132 ansible_user=alvaro
equipo4 ansible_host=192.168.15.131 ansible_user=alvaro
equipo5 ansible_host=192.168.15.134 ansible_user=alvaro
[sftp]
equipo1 ansible_host=192.168.15.138 ansible_user=alvaro
[prueba]
trabajo-Virtualbox 	ansible_host=192.168.15.145	ansible_user=alvaro